# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeting.proto

require 'google/protobuf'


descriptor_data = "\n\x0egreeting.proto\x12\x05greet\"\x1c\n\x0cGreetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rGreetResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8c\x02\n\x0cGreetService\x12\x35\n\x08SayHello\x12\x13.greet.GreetRequest\x1a\x14.greet.GreetResponse\x12@\n\x11SayHelloManyTimes\x12\x13.greet.GreetRequest\x1a\x14.greet.GreetResponse0\x01\x12@\n\x11SayHelloAllAtOnce\x12\x13.greet.GreetRequest\x1a\x14.greet.GreetResponse(\x01\x12\x41\n\x10sayHelloOneByOne\x12\x13.greet.GreetRequest\x1a\x14.greet.GreetResponse(\x01\x30\x01\x42 \n\x10spring_boot.grpcB\nGreetProtoP\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Greet
  GreetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.GreetRequest").msgclass
  GreetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.GreetResponse").msgclass
end
