spring:
  application:
    name: grpc-client
grpc:
  client:
    greeting-grpc-server:
      address: "static://localhost:9090"
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      ssl:
        enabled: false